lib/report/replica/schemas/declarations_status_hstr.ex, priv/repo/migrations/20170718124031_create_declarations_status_hstr.exs, specs/reporitng.erd
https://github.com/Nebo15/ehealth.api/issues/646
=> add declarations_status_hstr table schema and migration

specs/reporitng.erd, specs/reporting.erd
to reflect changes in [prm.erd](https://github.com/Nebo15/ehealth.api/pull/645)
=> declarations_status_hstr added

lib/report/stats/main_stats.ex, lib/report/web/controllers/stats_controller.ex, lib/report/web/router.ex, test/data/stats/division_stats_response.json, test/integration/stats/main_stats_test.exs, test/unit/web/controllers/stats_controller_test.exs
https://github.com/Nebo15/ehealth.api/issues/437
=> add main stats by divisions endpoint

lib/report/replica/replicas.ex, lib/report/replica/schemas/declarations_status_hstr.ex, lib/report/stats/main_stats.ex, lib/report/stats/regions_stats_request.ex, lib/report/web/controllers/fallback_controller.ex, lib/report/web/controllers/stats_controller.ex, lib/report/web/router.ex, lib/report/web/views/stats_view.ex, test/data/stats/regions_stats_response.json, test/integration/stats/main_stats_test.exs, test/support/factory.ex, test/unit/web/controllers/stats_controller_test.exs
https://github.com/Nebo15/ehealth.api/issues/432
=> add main stats by regions

lib/report/stats/main_stats.ex, test/unit/web/controllers/stats_controller_test.exs
https://github.com/Nebo15/ehealth.api/issues/432
=> return 404 if region was not found by id

specs/reporting.erd
* red_msps added
* red_msps_territories added
* streets adjusted
=> Red lists added

lib/report/replica/replicas.ex, lib/report/stats/division_stats.ex, lib/report/stats/division_stats_validator.ex, lib/report/stats/divisions_map_request.ex, lib/report/web/controllers/stats_controller.ex, lib/report/web/router.ex, lib/report/web/views/stats_view.ex, test/data/stats/divisions_map_response.json, test/integration/stats/division_stats_test.exs, test/unit/web/controllers/stats_controller_test.exs
https://github.com/EDENLABLLC/ehealth.api/issues/438
=> create divisions map endpoint

lib/report/web/views/stats_view.ex, test/data/stats/divisions_map_response.json
https://github.com/edenlabllc/ehealth.api/issues/438
=> fix divisions map response structure

lib/report/replica/replicas.ex, lib/report/stats/division_stats.ex, test/integration/stats/division_stats_test.exs
https://github.com/edenlabllc/ehealth.api/issues/438
=> add status and is_active filters to divisions map

config/config.exs, config/dev.exs, config/test.exs, lib/report/billing/billing.ex, lib/report/billing/billings.ex, lib/report/media_storage.ex, priv/repo/migrations/20170804131248_add_is_valid_to_billing.exs, test/support/mock_server.ex, test/test_helper.exs, test/unit/reporter_test.exs
https://github.com/edenlabllc/ehealth.api/issues/725
Please **do not merge** until ael endpoint for validation is done
=> Capitation signed content

lib/report/stats/main_stats.ex, test/integration/stats/main_stats_test.exs
https://github.com/edenlabllc/ehealth.api/issues/1084
=> include pending declarations to main stats

lib/report/stats/main_stats.ex, test/integration/stats/main_stats_test.exs
https://github.com/edenlabllc/ehealth.api/issues/1084
=> add pending to all declaration stats

lib/report/connection.ex, lib/report/replica/schemas/medical_program.ex, lib/report/replica/schemas/medication.ex, lib/report/replica/schemas/medication_dispense.ex, lib/report/replica/schemas/medication_dispense_details.ex, lib/report/replica/schemas/medication_dispense_status_hstr.ex, lib/report/replica/schemas/medication_request.ex, lib/report/replica/schemas/meta/document.ex, lib/report/replica/schemas/meta/phone.ex, lib/report/replica/schemas/party.ex, lib/report/stats/reimbursement_request.ex, lib/report/stats/reimbursement_stats.ex, lib/report/stats/reimbursement_stats_validator.ex, lib/report/web/controllers/fallback_controller.ex, lib/report/web/controllers/reimbursement_controller.ex, lib/report/web/router.ex, lib/report/web/views/reimbursement_view.ex, priv/repo/migrations/20170602914044_create_parties_table.exs, priv/repo/migrations/20171003143812_create_medications_table.exs, priv/repo/migrations/20171003144037_create_medical_programs_table.exs, priv/repo/migrations/20171003144141_create_medication_requests_table.exs, priv/repo/migrations/20171003144800_create_medication_dispenses_table.exs, priv/repo/migrations/20171003144952_create_medication_dispense_details_table.exs, priv/repo/migrations/20171003145051_create_medication_dispense_status_hstr_table.exs, specs/schemas/reimbursement_report_response.json, test/integration/stats/main_stats_test.exs, test/support/factory.ex, test/unit/web/controllers/reimbursement_controller_test.exs
https://github.com/edenlabllc/ehealth.api/issues/1157
=> create reimbursement report 

lib/report/replica/schemas/medication_request_status_hstr.ex, lib/report/stats/main_stats.ex, priv/repo/migrations/20171006083826_create_medication_requests_status_hstr.exs, test/data/stats/histogram_stats_response.json, test/data/stats/main_stats_response.json, test/data/stats/regions_stats_response.json, test/integration/stats/main_stats_test.exs, test/support/factory.ex
https://github.com/edenlabllc/ehealth.api/issues/1161
=> add reimbursement stats to portal

lib/report/stats/main_stats.ex
https://github.com/edenlabllc/ehealth.api/issues/1161
=> add new values to regions stats

lib/report/web/views/reimbursement_view.ex
https://github.com/edenlabllc/ehealth.api/issues/1157
=> fix rendering medications for reimbursement report

lib/report/web/views/reimbursement_view.ex
https://github.com/edenlabllc/ehealth.api/issues/1157
=> revert details render fix

specs/reporting.erd
Added new tables to reporting.erd
=> Reporting erd update

lib/report/stats/reimbursement_stats.ex
https://github.com/edenlabllc/ehealth.api/issues/1161
=> fix legal_entities filter for portal reimbursement

lib/report/stats/reimbursement_stats.ex, lib/report/web/views/reimbursement_view.ex, specs/schemas/reimbursement_report_response.json, test/unit/web/controllers/reimbursement_controller_test.exs
https://github.com/edenlabllc/ehealth.api/issues/1157
=> fix pagination in reimbursement report

lib/report/stats/division_stats_validator.ex, lib/report/stats/divisions_map_request.ex, test/integration/stats/division_stats_test.exs
https://github.com/edenlabllc/ehealth.api/issues/1350
=> add new values to division types

lib/report/replica/schemas/innm.ex, lib/report/replica/schemas/innm_dosage_ingredient.ex, lib/report/stats/reimbursement_csv_request.ex, lib/report/stats/reimbursement_stats_csv.ex, lib/report/stats/reimbursement_stats_validator.ex, lib/report/web/controllers/reimbursement_controller.ex, lib/report/web/router.ex, priv/repo/migrations/20171117125013_create_innms.exs, priv/repo/migrations/20171117125314_create_innm_dosage_ingredients.exs, test/support/factory.ex, test/unit/web/controllers/reimbursement_controller_test.exs
https://github.com/edenlabllc/ehealth.api/issues/1501
=> [patch] create reimbursement report csv

lib/report/replica/schemas/party.ex, priv/repo/migrations/20180301093642_add_party_declaration_count.exs
https://github.com/edenlabllc/ehealth.api/issues/1838
=> [patch] manage party declarations counter

lib/report/replica/schemas/employee.ex, lib/report/replica/schemas/party.ex, priv/repo/migrations/20180302082909_add_party_fields.exs, priv/repo/migrations/20180302084150_add_speciality_to_employee.exs
https://github.com/edenlabllc/ehealth.api/issues/1890
=> [patch] add replica fields

lib/report/employees/employees.ex, lib/report/employees/search.ex, lib/report/replica/schemas/party.ex, lib/report/web/controllers/employee_controller.ex, lib/report/web/router.ex, lib/report/web/views/employee_view.ex, priv/repo/migrations/20180303110821_add_fields_to_parties.exs, test/integration/stats/main_stats_test.exs, test/support/factory.ex, test/unit/web/controllers/employee_controller_test.exs
https://github.com/edenlabllc/ehealth.api/issues/1892
=> [patch] create employees list endpoint

lib/report/stats/main_stats.ex, test/support/factory.ex
https://github.com/edenlabllc/ehealth.api/issues/1877
=> [patch] get stats by residence address

lib/report/employees/employees.ex, lib/report/employees/search.ex, priv/repo/migrations/20180315102530_add_parties_full_text_index.exs, test/unit/web/controllers/employee_controller_test.exs
https://github.com/edenlabllc/ehealth.api/issues/1921
=> [patch] improve doctor search from cabinet

lib/report/web/views/employee_view.ex
https://github.com/edenlabllc/ehealth.api/issues/1892
=> [patch] fix doctors search response

lib/report/employees/employees.ex, lib/report/web/controllers/employee_controller.ex, lib/report/web/router.ex, lib/report/web/views/employee_view.ex, test/unit/web/controllers/employee_controller_test.exs
https://github.com/edenlabllc/ehealth.api/issues/1892
=> [patch] add employee show endpoint

config/config.exs, lib/report/application.ex, lib/report/stats/cache/cache.ex, lib/report/stats/cache/main_stats.ex, lib/report/stats/cache/region_stats.ex, lib/report/web/controllers/stats_controller.ex, lib/report/web/views/stats_view.ex
https://github.com/edenlabllc/ehealth.api/issues/2161
=> [minor] add main and regions stats caching

lib/report/web/views/reimbursement_view.ex
Add dispensed_by field to reimbursement response
=> [minor] Add dispensed_by field to reimbursement response

specs/schemas/reimbursement_report_response.json
Add dispensed_by field to json schema
=> [minor] Add dispensed_by field to json schema

lib/report/employees/employees.ex, lib/report/employees/search.ex, lib/report/web/views/employee_view.ex, test/data/stats/employee_stats_details_response.json, test/data/stats/employee_stats_response.json, test/support/factory.ex, test/unit/web/controllers/employee_controller_test.exs
https://github.com/edenlabllc/ehealth.api/issues/1892
=> [minor] fix employee stats

config/dev.exs, lib/report/replica/division_address.ex, lib/report/stats/main_stats.ex, priv/repo/migrations/20180515113934_create_division_addresses_table.exs
=> [minor] Add migration and schema for division addresses

lib/report/replica/schemas/division.ex, lib/report/stats/main_stats.ex, test/integration/stats/main_stats_test.exs, test/support/factory.ex
https://github.com/edenlabllc/ehealth.api/issues/2332
=> [minor] use division_addresses for stats

priv/repo/migrations/20180604143407_create_contracts.exs, priv/repo/migrations/20180604143508_create_contract_divisions.exs, priv/repo/migrations/20180604143543_create_contract_employees.exs
https://github.com/edenlabllc/ehealth.api/issues/2352
=> [minor] add contract tables to schema

priv/repo/migrations/20180604143407_create_contracts.exs
https://github.com/edenlabllc/ehealth.api/issues/2477
=> [minor] drop nhs_payment_details

lib/report/capitation/capitation_report.ex, lib/report/capitation/capitation_report_detail.ex, lib/report/capitation/capitation_report_error.ex, priv/repo/migrations/20180620123343_create_capitation_reports.exs, priv/repo/migrations/20180620123402_create_capitation_report_details.exs, priv/repo/migrations/20180620123407_create_capitation_report_errors.exs
https://github.com/edenlabllc/ehealth.api/issues/2391
=> [minor] create capitation migrations and schemas
